### ISSUE TITLE
Items purchased by Rakesh for GST filing

### ISSUE THREAD

**Issue by rakeshg1806** [IRIS-Retail-Pvt-Ltd/amazon#42]

**Comment by rakeshg1806** [comment]
[ChargeableLight.pdf](https://github.com/IRIS-Retail-Pvt-Ltd/amazon/files/4983035/ChargeableLight.pdf)
[Extender.pdf](https://github.com/IRIS-Retail-Pvt-Ltd/amazon/files/4983037/Extender.pdf)
[Sanitizer.pdf](https://github.com/IRIS-Retail-Pvt-Ltd/amazon/files/4983039/Sanitizer.pdf)

Sandeep, please find attached the files for GST filing.

**Comment by sandeepvalapi** [comment]
This cannot be an issue, Hence closing this
